# Controls when the action will run. Triggers the workflow on push request for the master branch
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to LeanEngine
      uses: enflo/curl-action@v1.2
      with:
        curl: -X POST https://leancloud.cn/1.1/engine/groups/web/staging/version?gitTag=${{ github.sha }}&token=${{ secrets.DEPLOY_TOKEN }}